from socket import socket, AddressFamily, SocketKind
from typing import Any, Tuple, overload


class usocket(socket):
    def __init__(
        self,
        family: AddressFamily | int = ...,
        type: SocketKind | int = ...,
        proto: int = ...,
        fileno: int | None = ...,
        *,
        fiabilite: float = ...,
        taux_corruption: float = ...,
    ) -> None: ...

    def send(self, data: bytes, flags: int = 0) -> int: ...
    @overload
    def sendto(self, data: bytes, address: Any) -> int: ...
    @overload
    def sendto(self, data: bytes, flags: int, address: Any) -> int: ...
    def sendall(self, data: bytes, flags: int = 0) -> None: ...
    def recv(self, bufsize: int, flags: int = 0) -> bytes: ...
    def recvfrom(self, bufsize: int, flags: int = 0) -> Tuple[bytes, Any]: ...
    def recv_into(self, buffer: Any, nbytes: int = 0, flags: int = 0) -> int: ...
    def recvfrom_into(
        self, buffer: Any, nbytes: int = 0, flags: int = 0
    ) -> Tuple[int, Any]: ...
    def update_fiabilite(self, fiabilite: float) -> None: ...
    def update_taux_corruption(self, taux_corruption: float) -> None: ...
